# -*- coding: utf-8 -*-
"""16262865-GEN AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yQhl2reb7AeNOwkVxL6XYjvCxSbg1Qj
"""

import torch, platform, os
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)
print("Torch:", torch.__version__)

!pip -q uninstall -y numpy pandas transformers datasets evaluate accelerate peft

!pip -q install "transformers==4.41.2" "datasets==2.19.1" "evaluate==0.4.1" "accelerate==0.30.1" "peft==0.11.1" rouge-score nltk

import numpy as np, pandas as pd, torch
import transformers, datasets, evaluate, accelerate
from peft import __version__ as peft_version

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("evaluate:", evaluate.__version__)
print("accelerate:", accelerate.__version__)
print("peft:", peft_version)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)

from datasets import load_dataset, Dataset
import re, random
random.seed(42)

# ----------------------------
# 1) Load SQuAD v2
# ----------------------------
squad = load_dataset("squad_v2")
print("SQuAD v2 loaded:", squad)

# ----------------------------
# 2) Load FinQA (try common dataset IDs)
# ----------------------------
finqa = None
finqa_candidates = [
    "finqa",
    "dreamerdeo/finqa",      # sometimes exists as a community mirror
    "ibm/finqa",             # sometimes used
    "gaussalgo/FinQA",       # sometimes used
]
for name in finqa_candidates:
    try:
        finqa = load_dataset(name)
        print("FinQA loaded as:", name)
        break
    except Exception as e:
        last_err = e

if finqa is None:
    print("❌ Could not load FinQA from candidates. Last error:\n", last_err)
    raise RuntimeError("FinQA not found in your datasets registry. Paste the error and I'll give the exact working ID.")

print("FinQA splits:", finqa)

def linearize_table(table):
    """Convert a FinQA table to compact text. Works for list-of-lists or pre-serialized strings."""
    if table is None:
        return ""
    if isinstance(table, str):
        return table
    lines = []
    for r_i, row in enumerate(table):
        if row is None:
            continue
        if isinstance(row, (list, tuple)):
            cells = [str(c) for c in row]
            lines.append(f"Row{r_i}: " + " | ".join(cells))
        else:
            lines.append(f"Row{r_i}: {row}")
    return "\n".join(lines)

def build_finqa_context(ex):
    pre = " ".join(ex.get("pre_text", []) or [])
    post = " ".join(ex.get("post_text", []) or [])
    table_txt = linearize_table(ex.get("table", None))
    parts = []
    if pre.strip(): parts.append("PRE: " + pre.strip())
    if table_txt.strip(): parts.append("TABLE:\n" + table_txt.strip())
    if post.strip(): parts.append("POST: " + post.strip())
    return "\n\n".join(parts).strip()

def extract_finqa_answer(ex):
    # Try common keys across variants
    for key in ["final_answer", "answer", "gold_answer", "target", "output"]:
        if key in ex and ex[key] not in (None, ""):
            return str(ex[key]).strip()
    # Sometimes answers are nested
    if "qa" in ex and isinstance(ex["qa"], dict):
        for key in ["answer", "final_answer"]:
            if key in ex["qa"] and ex["qa"][key]:
                return str(ex["qa"][key]).strip()
    return ""

def make_prompt(context, question):
    return (
        "You are given a context and a question.\n"
        "Answer using ONLY the information in the context.\n"
        "If the answer is not present in the context, output exactly: No answer\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )

from datasets import Dataset

def is_unanswerable_squad(ex):
    # Preferred explicit flag
    if "is_impossible" in ex:
        return bool(ex["is_impossible"])
    # Fallback: no answers provided => unanswerable
    ans = ex.get("answers", {})
    texts = ans.get("text", []) if isinstance(ans, dict) else []
    return len(texts) == 0

def get_first_answer_text(ex):
    ans = ex.get("answers", {})
    texts = ans.get("text", []) if isinstance(ans, dict) else []
    if len(texts) == 0:
        return "No answer"
    return str(texts[0])

def unify_squad(split):
    rows = []
    for ex in split:
        unans = is_unanswerable_squad(ex)
        ans_text = "No answer" if unans else get_first_answer_text(ex)
        rows.append({
            "id": ex.get("id", ""),
            "dataset": "squad_v2",
            "context": ex.get("context", ""),
            "question": ex.get("question", ""),
            "answer": ans_text,
            "is_impossible": unans,
        })
    return Dataset.from_list(rows)

# retry
squad_train = unify_squad(squad["train"])
squad_val   = unify_squad(squad["validation"])
print("SQuAD unified train/val:", len(squad_train), len(squad_val))

unans_rate = sum(squad_train["is_impossible"]) / len(squad_train)
print("Unanswerable rate (train):", unans_rate)

unans_rate_val = sum(squad_val["is_impossible"]) / len(squad_val)
print("Unanswerable rate (val):", unans_rate_val)

from datasets import load_dataset, Dataset

# Load FinQA (try several IDs)
finqa = None
cands = ["finqa", "ibm/finqa", "gaussalgo/FinQA", "dreamerdeo/finqa"]
last_err = None

for name in cands:
    try:
        finqa = load_dataset(name)
        print("✅ FinQA loaded as:", name)
        break
    except Exception as e:
        last_err = e

if finqa is None:
    print("❌ Failed to load FinQA. Last error:\n", last_err)
    raise RuntimeError("FinQA not found. Paste the error and I'll give the exact working dataset ID.")

print("FinQA split keys:", list(finqa.keys()))

import re

def linearize_table(table):
    if table is None:
        return ""
    if isinstance(table, str):
        return table
    lines = []
    for r_i, row in enumerate(table):
        if row is None:
            continue
        if isinstance(row, (list, tuple)):
            lines.append(f"Row{r_i}: " + " | ".join([str(x) for x in row]))
        else:
            lines.append(f"Row{r_i}: {row}")
    return "\n".join(lines)

def build_finqa_context(ex):
    pre = " ".join(ex.get("pre_text", []) or [])
    post = " ".join(ex.get("post_text", []) or [])
    table_txt = linearize_table(ex.get("table", None))
    parts = []
    if pre.strip(): parts.append("PRE: " + pre.strip())
    if table_txt.strip(): parts.append("TABLE:\n" + table_txt.strip())
    if post.strip(): parts.append("POST: " + post.strip())
    return "\n\n".join(parts).strip()

def extract_finqa_answer(ex):
    for key in ["final_answer", "answer", "gold_answer", "target", "output"]:
        if key in ex and ex[key] not in (None, ""):
            return str(ex[key]).strip()
    if "qa" in ex and isinstance(ex["qa"], dict):
        for key in ["answer", "final_answer"]:
            if key in ex["qa"] and ex["qa"][key]:
                return str(ex["qa"][key]).strip()
    return ""

def unify_finqa(split):
    rows = []
    for ex in split:
        ctx = build_finqa_context(ex)
        q = ex.get("question", ex.get("qa", {}).get("question", ""))
        a = extract_finqa_answer(ex)
        if not ctx or not q or not a:
            continue
        rows.append({
            "id": str(ex.get("id", ex.get("uid", len(rows)))),
            "dataset": "finqa",
            "context": ctx,
            "question": q,
            "answer": a,
            "is_impossible": False
        })
    return Dataset.from_list(rows)

# identify train/val splits
train_key = "train" if "train" in finqa else ("training" if "training" in finqa else None)
val_key = "validation" if "validation" in finqa else ("dev" if "dev" in finqa else ("val" if "val" in finqa else ("test" if "test" in finqa else None)))

print("Chosen splits:", train_key, val_key)
if train_key is None or val_key is None:
    raise RuntimeError(f"Can't find FinQA train/val. Keys={list(finqa.keys())}")

finqa_train = unify_finqa(finqa[train_key])
finqa_val   = unify_finqa(finqa[val_key])

print("FinQA unified train/val:", len(finqa_train), len(finqa_val))

def sample_ds(ds, n, seed=42):
    n = min(n, len(ds))
    return ds.shuffle(seed=seed).select(range(n))

SQUAD_TRAIN_N = 12000
SQUAD_VAL_N   = 1500
FINQA_TRAIN_N = 12000
FINQA_VAL_N   = 1500

squad_train_s = sample_ds(squad_train, SQUAD_TRAIN_N)
squad_val_s   = sample_ds(squad_val,   SQUAD_VAL_N)

finqa_train_s = sample_ds(finqa_train, FINQA_TRAIN_N)
finqa_val_s   = sample_ds(finqa_val,   FINQA_VAL_N)

print("Subsampled sizes:")
print("SQuAD train/val:", len(squad_train_s), len(squad_val_s))
print("FinQA train/val:", len(finqa_train_s), len(finqa_val_s))

import os, json, math, re
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

os.environ["TRANSFORMERS_NO_TF"] = "1"
os.environ["TRANSFORMERS_NO_FLAX"] = "1"

device = "cuda" if torch.cuda.is_available() else "cpu"
model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)
model.eval()

def make_prompt(context, question):
    return (
        "You are given a context and a question.\n"
        "Answer using ONLY the information in the context.\n"
        "If the answer is not present in the context, output exactly: No answer\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )

@torch.inference_mode()
def generate_with_conf(prompt, max_new_tokens=64):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)

    # Generate
    gen_out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        num_beams=1,
        return_dict_in_generate=True,
        output_scores=True,
    )
    seq = gen_out.sequences[0]  # token ids (includes input for some models; for T5 it's decoder output ids)
    text = tokenizer.decode(seq, skip_special_tokens=True).strip()

    # Confidence: avg log-prob of generated tokens (decoder side)
    # scores: list over time steps, each is (vocab logits)
    scores = gen_out.scores
    # Align tokens: for seq2seq, sequences are decoder tokens; first token often is pad/start; we align by taking last len(scores) tokens
    gen_token_ids = seq[-len(scores):]

    logps = []
    for t, (logits, tok_id) in enumerate(zip(scores, gen_token_ids)):
        logprob = torch.log_softmax(logits[0], dim=-1)[tok_id].item()
        logps.append(logprob)

    avg_logp = float(sum(logps) / max(1, len(logps)))
    return text, avg_logp

# ---------- Normalizers ----------
def norm_text(s):
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

def extract_numbers(s):
    # captures integers, decimals, percentages, negatives
    return re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?%?", s)

def context_contains_answer(context, pred):
    # Evidence Support Score proxy: substring after normalization
    c = norm_text(context)
    p = norm_text(pred)
    if p == "" or p == "no answer":
        return True  # abstention considered supported
    return p in c

# ---------- Metrics ----------
def squad_em_f1(pred, gold):
    # simple EM/F1 for single gold string (SQuAD v2 has multiple, but we're using first)
    p = norm_text(pred)
    g = norm_text(gold)

    em = 1 if p == g else 0

    # token F1
    p_toks = p.split()
    g_toks = g.split()
    if len(p_toks) == 0 and len(g_toks) == 0:
        return em, 1.0
    if len(p_toks) == 0 or len(g_toks) == 0:
        return em, 0.0
    common = {}
    for t in p_toks:
        common[t] = common.get(t, 0) + 1
    num_same = 0
    g_count = {}
    for t in g_toks:
        g_count[t] = g_count.get(t, 0) + 1
    for t in common:
        if t in g_count:
            num_same += min(common[t], g_count[t])
    if num_same == 0:
        return em, 0.0
    precision = num_same / len(p_toks)
    recall = num_same / len(g_toks)
    f1 = (2 * precision * recall) / (precision + recall)
    return em, f1

def compute_uhr(rows):
    # Unanswerable Hallucination Rate: on is_impossible examples, fraction not "No answer"
    unans = [r for r in rows if r["is_impossible"]]
    if not unans:
        return None
    hall = sum(1 for r in unans if norm_text(r["pred"]) != "no answer")
    return hall / len(unans)

def compute_ess(rows):
    # Evidence Support Score proxy
    supported = sum(1 for r in rows if context_contains_answer(r["context"], r["pred"]))
    return supported / len(rows) if rows else None

def compute_nhr(rows):
    # Number Hallucination Rate for FinQA: predicted numbers not present in context
    num_preds = 0
    hall = 0
    for r in rows:
        pred_nums = extract_numbers(r["pred"])
        if not pred_nums:
            continue
        num_preds += 1
        ctx_nums = set(extract_numbers(r["context"]))
        # hallucinated if ANY predicted number not in context
        if any(n not in ctx_nums for n in pred_nums):
            hall += 1
    return (hall / num_preds) if num_preds > 0 else None

# ---------- Run baseline eval ----------
def run_eval(ds, out_path, limit=None):
    rows = []
    n = len(ds) if limit is None else min(limit, len(ds))
    for i in range(n):
        ex = ds[i]
        prompt = make_prompt(ex["context"], ex["question"])
        pred, avg_logp = generate_with_conf(prompt)
        row = {
            "id": ex["id"],
            "dataset": ex["dataset"],
            "question": ex["question"],
            "context": ex["context"],
            "gold": ex["answer"],
            "is_impossible": bool(ex["is_impossible"]),
            "pred": pred,
            "avg_logp": avg_logp,
        }
        rows.append(row)

        if (i+1) % 50 == 0:
            print(f"{out_path}: {i+1}/{n} done")

    with open(out_path, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    return rows

# Run (keep full FinQA val; SQuAD val is 1500)
baseline_squad_rows = run_eval(squad_val_s, "baseline_squad.jsonl", limit=None)
baseline_finqa_rows = run_eval(finqa_val_s, "baseline_finqa.jsonl", limit=None)

# Compute baseline metrics
# SQuAD: EM/F1 on answerable only + UHR on unanswerables
squad_answerable = [r for r in baseline_squad_rows if not r["is_impossible"]]
ems, f1s = [], []
for r in squad_answerable:
    em, f1 = squad_em_f1(r["pred"], r["gold"])
    ems.append(em); f1s.append(f1)

print("\n=== BASELINE RESULTS ===")
print("SQuAD answerable EM:", sum(ems)/len(ems))
print("SQuAD answerable F1:", sum(f1s)/len(f1s))
print("SQuAD UHR (unanswerable hallucination rate):", compute_uhr(baseline_squad_rows))
print("SQuAD ESS (evidence support proxy):", compute_ess(baseline_squad_rows))

# FinQA: exact match proxy + NHR + ESS
finqa_em = sum(1 for r in baseline_finqa_rows if norm_text(r["pred"]) == norm_text(r["gold"])) / len(baseline_finqa_rows)
print("FinQA exact match (strict):", finqa_em)
print("FinQA NHR (number hallucination rate):", compute_nhr(baseline_finqa_rows))
print("FinQA ESS (evidence support proxy):", compute_ess(baseline_finqa_rows))

from transformers import DataCollatorForSeq2Seq
import numpy as np

def preprocess_batch(batch):
    prompts = [make_prompt(c, q) for c, q in zip(batch["context"], batch["question"])]
    model_inputs = tokenizer(prompts, max_length=512, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["answer"], max_length=64, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

finqa_train_tok = finqa_train.map(preprocess_batch, batched=True, remove_columns=finqa_train.column_names)
finqa_val_tok   = finqa_val.map(preprocess_batch, batched=True, remove_columns=finqa_val.column_names)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
print("Tokenized FinQA:", finqa_train_tok, finqa_val_tok)

from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    # T5 attention modules - PEFT will match names present in model
    target_modules=["q", "v"]  # works for T5; if it errors, we’ll switch to the exact module names from your model
)

lora_model = get_peft_model(model, lora_config)
lora_model.print_trainable_parameters()

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

args = Seq2SeqTrainingArguments(
    output_dir="lora_finqa_only",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    num_train_epochs=2,
    logging_steps=50,
    evaluation_strategy="steps",
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    predict_with_generate=True,
    generation_max_length=64,
    fp16=False,
    bf16=True,  # A100
    report_to="none"
)

trainer = Seq2SeqTrainer(
    model=lora_model,
    args=args,
    train_dataset=finqa_train_tok,
    eval_dataset=finqa_val_tok,
    data_collator=data_collator,
    tokenizer=tokenizer,
)

trainer.train()

lora_model.save_pretrained("adapter_finqa_only")
tokenizer.save_pretrained("adapter_finqa_only")
print("Saved adapter to adapter_finqa_only/")

import os, json, re
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from peft import PeftModel

os.environ["TRANSFORMERS_NO_TF"] = "1"
device = "cuda" if torch.cuda.is_available() else "cpu"

base_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(base_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_name).to(device)
model_finqa = PeftModel.from_pretrained(base_model, "adapter_finqa_only").to(device)
model_finqa.eval()

def norm_text(s):
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

def extract_numbers(s):
    return re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?%?", s)

def context_contains_answer(context, pred):
    c = norm_text(context)
    p = norm_text(pred)
    if p == "" or p == "no answer":
        return True
    return p in c

def make_prompt(context, question):
    return (
        "You are given a context and a question.\n"
        "Answer using ONLY the information in the context.\n"
        "If the answer is not present in the context, output exactly: No answer\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )

@torch.inference_mode()
def generate_with_conf(model, prompt, max_new_tokens=64):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        num_beams=1,
        return_dict_in_generate=True,
        output_scores=True,
    )
    seq = out.sequences[0]
    text = tokenizer.decode(seq, skip_special_tokens=True).strip()

    scores = out.scores
    gen_token_ids = seq[-len(scores):]

    logps = []
    for logits, tok_id in zip(scores, gen_token_ids):
        logp = torch.log_softmax(logits[0], dim=-1)[tok_id].item()
        logps.append(logp)

    avg_logp = float(sum(logps) / max(1, len(logps)))
    return text, avg_logp

def squad_em_f1(pred, gold):
    p = norm_text(pred); g = norm_text(gold)
    em = 1 if p == g else 0
    p_toks, g_toks = p.split(), g.split()
    if len(p_toks) == 0 and len(g_toks) == 0: return em, 1.0
    if len(p_toks) == 0 or len(g_toks) == 0: return em, 0.0
    from collections import Counter
    common = Counter(p_toks) & Counter(g_toks)
    num_same = sum(common.values())
    if num_same == 0: return em, 0.0
    precision = num_same / len(p_toks)
    recall = num_same / len(g_toks)
    f1 = 2 * precision * recall / (precision + recall)
    return em, f1

def compute_uhr(rows):
    unans = [r for r in rows if r["is_impossible"]]
    hall = sum(1 for r in unans if norm_text(r["pred"]) != "no answer")
    return hall / len(unans) if unans else None

def compute_ess(rows):
    supported = sum(1 for r in rows if context_contains_answer(r["context"], r["pred"]))
    return supported / len(rows) if rows else None

def compute_nhr(rows):
    num_preds = 0; hall = 0
    for r in rows:
        pred_nums = extract_numbers(r["pred"])
        if not pred_nums:
            continue
        num_preds += 1
        ctx_nums = set(extract_numbers(r["context"]))
        if any(n not in ctx_nums for n in pred_nums):
            hall += 1
    return (hall / num_preds) if num_preds else None

def finqa_strict_em(rows):
    return sum(1 for r in rows if norm_text(r["pred"]) == norm_text(r["gold"])) / len(rows)

def finqa_numeric_em(rows):
    # If gold contains a number, check if any predicted number matches any gold number
    good = 0
    total = 0
    for r in rows:
        gnums = extract_numbers(r["gold"])
        pnums = extract_numbers(r["pred"])
        if not gnums:
            # fallback: string match for non-numeric
            total += 1
            good += 1 if norm_text(r["pred"]) == norm_text(r["gold"]) else 0
            continue
        total += 1
        good += 1 if any(pn == gn for pn in pnums for gn in gnums) else 0
    return good / total if total else None

def run_eval(model, ds, out_path, limit=None):
    rows = []
    n = len(ds) if limit is None else min(limit, len(ds))
    for i in range(n):
        ex = ds[i]
        prompt = make_prompt(ex["context"], ex["question"])
        pred, avg_logp = generate_with_conf(model, prompt)
        rows.append({
            "id": ex["id"],
            "dataset": ex["dataset"],
            "question": ex["question"],
            "context": ex["context"],
            "gold": ex["answer"],
            "is_impossible": bool(ex["is_impossible"]),
            "pred": pred,
            "avg_logp": avg_logp,
        })
        if (i+1) % 50 == 0:
            print(f"{out_path}: {i+1}/{n} done")
    with open(out_path, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    return rows

finqa_only_squad_rows = run_eval(model_finqa, squad_val_s, "finqa_only_squad.jsonl")
finqa_only_finqa_rows = run_eval(model_finqa, finqa_val_s, "finqa_only_finqa.jsonl")

# SQuAD answerable metrics
squad_ans = [r for r in finqa_only_squad_rows if not r["is_impossible"]]
ems, f1s = zip(*[squad_em_f1(r["pred"], r["gold"]) for r in squad_ans])
squad_em = sum(ems)/len(ems)
squad_f1 = sum(f1s)/len(f1s)

print("\n=== FINQA-ONLY LoRA RESULTS ===")
print("SQuAD answerable EM:", squad_em)
print("SQuAD answerable F1:", squad_f1)
print("SQuAD UHR:", compute_uhr(finqa_only_squad_rows))
print("SQuAD ESS:", compute_ess(finqa_only_squad_rows))

print("FinQA strict EM:", finqa_strict_em(finqa_only_finqa_rows))
print("FinQA numeric EM:", finqa_numeric_em(finqa_only_finqa_rows))
print("FinQA NHR:", compute_nhr(finqa_only_finqa_rows))
print("FinQA ESS:", compute_ess(finqa_only_finqa_rows))

from datasets import concatenate_datasets

# Ensure SQuAD sample is same size as FinQA train
squad_train_bal = squad_train_s.shuffle(seed=42).select(range(len(finqa_train)))  # 6203

# Concatenate (balanced)
multitask_train = concatenate_datasets([finqa_train, squad_train_bal]).shuffle(seed=42)

print("FinQA train:", len(finqa_train))
print("SQuAD balanced train:", len(squad_train_bal))
print("Multi-task train:", len(multitask_train))

from transformers import DataCollatorForSeq2Seq

def preprocess_batch(batch):
    prompts = [make_prompt(c, q) for c, q in zip(batch["context"], batch["question"])]
    model_inputs = tokenizer(prompts, max_length=512, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["answer"], max_length=64, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

multitask_train_tok = multitask_train.map(preprocess_batch, batched=True, remove_columns=multitask_train.column_names)

# For eval during training, use a small mixed eval set to monitor loss (optional)
multitask_eval = concatenate_datasets([finqa_val, squad_val_s.shuffle(seed=42).select(range(871))]).shuffle(seed=42)
multitask_eval_tok = multitask_eval.map(preprocess_batch, batched=True, remove_columns=multitask_eval.column_names)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

print("Tokenized multitask train/eval:", multitask_train_tok, multitask_eval_tok)

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from peft import LoraConfig, get_peft_model, TaskType

device = "cuda" if torch.cuda.is_available() else "cpu"
base_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(base_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_name).to(device)

lora_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules=["q", "v"],  # same as before (worked)
)

lora_multitask = get_peft_model(base_model, lora_config).to(device)
lora_multitask.print_trainable_parameters()

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

args = Seq2SeqTrainingArguments(
    output_dir="lora_multitask_balanced",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    num_train_epochs=2,
    logging_steps=50,
    evaluation_strategy="steps",
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    predict_with_generate=True,
    generation_max_length=64,
    bf16=True,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=lora_multitask,
    args=args,
    train_dataset=multitask_train_tok,
    eval_dataset=multitask_eval_tok,
    data_collator=data_collator,
    tokenizer=tokenizer,
)

trainer.train()

lora_multitask.save_pretrained("adapter_multitask_balanced")
tokenizer.save_pretrained("adapter_multitask_balanced")
print("Saved adapter to adapter_multitask_balanced/")

import os, json, re
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from peft import PeftModel

os.environ["TRANSFORMERS_NO_TF"] = "1"
device = "cuda" if torch.cuda.is_available() else "cpu"

base_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(base_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_name).to(device)
model_mt = PeftModel.from_pretrained(base_model, "adapter_multitask_balanced").to(device)
model_mt.eval()

def norm_text(s):
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

def extract_numbers(s):
    return re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?%?", s)

def context_contains_answer(context, pred):
    c = norm_text(context)
    p = norm_text(pred)
    if p == "" or p == "no answer":
        return True
    return p in c

def make_prompt(context, question):
    return (
        "You are given a context and a question.\n"
        "Answer using ONLY the information in the context.\n"
        "If the answer is not present in the context, output exactly: No answer\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )

@torch.inference_mode()
def generate_with_conf(model, prompt, max_new_tokens=64):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        num_beams=1,
        return_dict_in_generate=True,
        output_scores=True,
    )
    seq = out.sequences[0]
    text = tokenizer.decode(seq, skip_special_tokens=True).strip()

    scores = out.scores
    gen_token_ids = seq[-len(scores):]

    logps = []
    for logits, tok_id in zip(scores, gen_token_ids):
        logp = torch.log_softmax(logits[0], dim=-1)[tok_id].item()
        logps.append(logp)

    avg_logp = float(sum(logps) / max(1, len(logps)))
    return text, avg_logp

def squad_em_f1(pred, gold):
    p = norm_text(pred); g = norm_text(gold)
    em = 1 if p == g else 0
    p_toks, g_toks = p.split(), g.split()
    if len(p_toks) == 0 and len(g_toks) == 0: return em, 1.0
    if len(p_toks) == 0 or len(g_toks) == 0: return em, 0.0
    from collections import Counter
    common = Counter(p_toks) & Counter(g_toks)
    num_same = sum(common.values())
    if num_same == 0: return em, 0.0
    precision = num_same / len(p_toks)
    recall = num_same / len(g_toks)
    f1 = 2 * precision * recall / (precision + recall)
    return em, f1

def compute_uhr(rows):
    unans = [r for r in rows if r["is_impossible"]]
    hall = sum(1 for r in unans if norm_text(r["pred"]) != "no answer")
    return hall / len(unans) if unans else None

def compute_ess(rows):
    supported = sum(1 for r in rows if context_contains_answer(r["context"], r["pred"]))
    return supported / len(rows) if rows else None

def compute_nhr(rows):
    num_preds = 0; hall = 0
    for r in rows:
        pred_nums = extract_numbers(r["pred"])
        if not pred_nums:
            continue
        num_preds += 1
        ctx_nums = set(extract_numbers(r["context"]))
        if any(n not in ctx_nums for n in pred_nums):
            hall += 1
    return (hall / num_preds) if num_preds else None

def finqa_strict_em(rows):
    return sum(1 for r in rows if norm_text(r["pred"]) == norm_text(r["gold"])) / len(rows)

def finqa_numeric_em(rows):
    good = 0; total = 0
    for r in rows:
        gnums = extract_numbers(r["gold"])
        pnums = extract_numbers(r["pred"])
        if not gnums:
            total += 1
            good += 1 if norm_text(r["pred"]) == norm_text(r["gold"]) else 0
        else:
            total += 1
            good += 1 if any(pn == gn for pn in pnums for gn in gnums) else 0
    return good / total if total else None

def run_eval(model, ds, out_path):
    rows = []
    n = len(ds)
    for i in range(n):
        ex = ds[i]
        prompt = make_prompt(ex["context"], ex["question"])
        pred, avg_logp = generate_with_conf(model, prompt)
        rows.append({
            "id": ex["id"],
            "dataset": ex["dataset"],
            "question": ex["question"],
            "context": ex["context"],
            "gold": ex["answer"],
            "is_impossible": bool(ex["is_impossible"]),
            "pred": pred,
            "avg_logp": avg_logp,
        })
        if (i+1) % 50 == 0:
            print(f"{out_path}: {i+1}/{n} done")
    with open(out_path, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    return rows

mt_squad_rows = run_eval(model_mt, squad_val_s, "multitask_squad.jsonl")
mt_finqa_rows = run_eval(model_mt, finqa_val_s, "multitask_finqa.jsonl")

squad_ans = [r for r in mt_squad_rows if not r["is_impossible"]]
ems, f1s = zip(*[squad_em_f1(r["pred"], r["gold"]) for r in squad_ans])
squad_em = sum(ems)/len(ems)
squad_f1 = sum(f1s)/len(f1s)

print("\n=== MULTITASK LoRA RESULTS ===")
print("SQuAD answerable EM:", squad_em)
print("SQuAD answerable F1:", squad_f1)
print("SQuAD UHR:", compute_uhr(mt_squad_rows))
print("SQuAD ESS:", compute_ess(mt_squad_rows))

print("FinQA strict EM:", finqa_strict_em(mt_finqa_rows))
print("FinQA numeric EM:", finqa_numeric_em(mt_finqa_rows))
print("FinQA NHR:", compute_nhr(mt_finqa_rows))
print("FinQA ESS:", compute_ess(mt_finqa_rows))

import numpy as np

def compute_oer(rows, percentile=80):
    # confidence = avg_logp (higher = more confident)
    confs = np.array([r["avg_logp"] for r in rows])
    threshold = np.percentile(confs, percentile)

    wrong = [r for r in rows if norm_text(r["pred"]) != norm_text(r["gold"])]
    if not wrong:
        return None

    overconf_wrong = [r for r in wrong if r["avg_logp"] >= threshold]
    return len(overconf_wrong) / len(wrong)

print("=== OER (80th percentile) ===")
print("Baseline SQuAD:", compute_oer(baseline_squad_rows))
print("Finance-only SQuAD:", compute_oer(finqa_only_squad_rows))
print("Multi-task SQuAD:", compute_oer(mt_squad_rows))

print("Baseline FinQA:", compute_oer(baseline_finqa_rows))
print("Finance-only FinQA:", compute_oer(finqa_only_finqa_rows))
print("Multi-task FinQA:", compute_oer(mt_finqa_rows))

import os, re, json, math, random
import numpy as np
import torch

os.environ["TRANSFORMERS_NO_TF"] = "1"
os.environ["TRANSFORMERS_NO_FLAX"] = "1"
torch.manual_seed(42)
random.seed(42)
np.random.seed(42)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("CUDA:", torch.cuda.is_available(), torch.cuda.get_device_name(0))

ex = finqa_train[0]
print(ex.keys())
print("question:", ex.get("question", None) or ex.get("qa", {}).get("question"))
print("candidate answer keys:",
      {k: ex.get(k) for k in ["final_answer","answer","gold_answer","target","output"] if k in ex})

def norm_text(s):
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

def clean_num_str(s):
    # remove currency symbols/commas/spaces
    s = s.strip()
    s = s.replace(",", "")
    s = re.sub(r"[$£€]", "", s)
    # convert percentages "12%" -> 12 (we will treat % specially if needed)
    return s

def to_float(x):
    try:
        return float(clean_num_str(x.replace("%","")))
    except:
        return None

def extract_numbers(s):
    return re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?%?", s)

def finqa_numeric_stats(rows):
    """
    Returns:
      - strict_em
      - numeric_exact_em
      - acc_abs_0_1: abs error <= 0.1
      - acc_rel_1pct: rel error <= 1%
      - mae, mape (on numeric cases)
    """
    strict_hits = 0
    num_exact_hits = 0
    abs_hits = 0
    rel_hits = 0
    abs_errors = []
    rel_errors = []

    numeric_cases = 0
    for r in rows:
        gold = r["gold"]
        pred = r["pred"]

        if norm_text(pred) == norm_text(gold):
            strict_hits += 1

        gnums = extract_numbers(gold)
        pnums = extract_numbers(pred)

        if not gnums:
            continue

        g = to_float(gnums[0])  # FinQA usually single final number
        if g is None:
            continue

        numeric_cases += 1
        # choose first numeric from prediction
        p = to_float(pnums[0]) if pnums else None
        if p is None:
            # no numeric pred -> huge error
            abs_errors.append(abs(g))
            rel_errors.append(abs(g) / (abs(g) + 1e-9))
            continue

        if abs(p - g) < 1e-9:
            num_exact_hits += 1

        abs_err = abs(p - g)
        abs_errors.append(abs_err)

        rel_err = abs_err / (abs(g) + 1e-9)
        rel_errors.append(rel_err)

        if abs_err <= 0.1:
            abs_hits += 1
        if rel_err <= 0.01:
            rel_hits += 1

    strict_em = strict_hits / len(rows)
    numeric_exact_em = (num_exact_hits / numeric_cases) if numeric_cases else None
    acc_abs_0_1 = (abs_hits / numeric_cases) if numeric_cases else None
    acc_rel_1pct = (rel_hits / numeric_cases) if numeric_cases else None
    mae = float(np.mean(abs_errors)) if abs_errors else None
    mape = float(np.mean(rel_errors)) if rel_errors else None

    return {
        "strict_em": strict_em,
        "numeric_exact_em": numeric_exact_em,
        "acc_abs_0_1": acc_abs_0_1,
        "acc_rel_1pct": acc_rel_1pct,
        "mae": mae,
        "mape": mape,
        "numeric_cases": numeric_cases
    }

def compute_nhr(rows):
    num_preds = 0; hall = 0
    for r in rows:
        pred_nums = extract_numbers(r["pred"])
        if not pred_nums:
            continue
        num_preds += 1
        ctx_nums = set(extract_numbers(r["context"]))
        if any(n not in ctx_nums for n in pred_nums):
            hall += 1
    return hall / num_preds if num_preds else None

def compute_oer(rows, percentile=80):
    confs = np.array([r["avg_logp"] for r in rows])
    thr = np.percentile(confs, percentile)
    wrong = [r for r in rows if norm_text(r["pred"]) != norm_text(r["gold"])]
    if not wrong:
        return None
    return sum(1 for r in wrong if r["avg_logp"] >= thr) / len(wrong)

print("Baseline FinQA stats:", finqa_numeric_stats(baseline_finqa_rows))
print("Finance-only FinQA stats:", finqa_numeric_stats(finqa_only_finqa_rows))
print("Multitask FinQA stats:", finqa_numeric_stats(mt_finqa_rows))
print("Baseline FinQA NHR:", compute_nhr(baseline_finqa_rows))
print("Finance-only FinQA NHR:", compute_nhr(finqa_only_finqa_rows))
print("Multitask FinQA NHR:", compute_nhr(mt_finqa_rows))

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

base_name = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(base_name)
fft_model = AutoModelForSeq2SeqLM.from_pretrained(base_name).to(device)

from transformers import DataCollatorForSeq2Seq

def make_prompt(context, question):
    return (
        "You are given a context and a question.\n"
        "Answer using ONLY the information in the context.\n"
        "If the answer is not present in the context, output exactly: No answer\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Answer:"
    )

def preprocess_batch(batch):
    prompts = [make_prompt(c, q) for c, q in zip(batch["context"], batch["question"])]
    model_inputs = tokenizer(prompts, max_length=512, truncation=True)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["answer"], max_length=64, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

finqa_train_tok = finqa_train.map(preprocess_batch, batched=True, remove_columns=finqa_train.column_names)
finqa_val_tok   = finqa_val.map(preprocess_batch, batched=True, remove_columns=finqa_val.column_names)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=fft_model)

fft_model.gradient_checkpointing_enable()
fft_model.config.use_cache = False

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

fft_args = Seq2SeqTrainingArguments(
    output_dir="fft_finqa_only",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=1e-4,          # FFT usually needs smaller LR than LoRA
    num_train_epochs=1,          # start with 1
    logging_steps=50,
    evaluation_strategy="steps",
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    predict_with_generate=True,
    generation_max_length=64,
    bf16=True,
    report_to="none",
)

fft_trainer = Seq2SeqTrainer(
    model=fft_model,
    args=fft_args,
    train_dataset=finqa_train_tok,
    eval_dataset=finqa_val_tok,
    data_collator=data_collator,
    tokenizer=tokenizer,
)

fft_trainer.train()
fft_trainer.save_model("fft_model_finqa_only")
tokenizer.save_pretrained("fft_model_finqa_only")
print("✅ Saved FFT model to fft_model_finqa_only/")

@torch.inference_mode()
def generate_with_conf(model, prompt, max_new_tokens=64):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        num_beams=1,
        return_dict_in_generate=True,
        output_scores=True,
    )
    seq = out.sequences[0]
    text = tokenizer.decode(seq, skip_special_tokens=True).strip()

    scores = out.scores
    gen_token_ids = seq[-len(scores):]
    logps = []
    for logits, tok_id in zip(scores, gen_token_ids):
        logp = torch.log_softmax(logits[0], dim=-1)[tok_id].item()
        logps.append(logp)

    avg_logp = float(sum(logps) / max(1, len(logps)))
    return text, avg_logp

def run_eval(model, ds, out_path):
    rows = []
    for i in range(len(ds)):
        ex = ds[i]
        prompt = make_prompt(ex["context"], ex["question"])
        pred, avg_logp = generate_with_conf(model, prompt)
        rows.append({
            "id": ex["id"],
            "dataset": ex["dataset"],
            "question": ex["question"],
            "context": ex["context"],
            "gold": ex["answer"],
            "is_impossible": bool(ex["is_impossible"]),
            "pred": pred,
            "avg_logp": avg_logp,
        })
        if (i+1) % 50 == 0:
            print(f"{out_path}: {i+1}/{len(ds)} done")
    with open(out_path, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    return rows

from collections import Counter

def squad_em_f1(pred, gold):
    p = norm_text(pred); g = norm_text(gold)
    em = 1 if p == g else 0
    p_toks, g_toks = p.split(), g.split()
    if len(p_toks) == 0 and len(g_toks) == 0: return em, 1.0
    if len(p_toks) == 0 or len(g_toks) == 0: return em, 0.0
    common = Counter(p_toks) & Counter(g_toks)
    num_same = sum(common.values())
    if num_same == 0: return em, 0.0
    precision = num_same / len(p_toks)
    recall = num_same / len(g_toks)
    f1 = 2 * precision * recall / (precision + recall)
    return em, f1

def compute_uhr(rows):
    unans = [r for r in rows if r["is_impossible"]]
    if not unans:
        return None
    hall = sum(1 for r in unans if norm_text(r["pred"]) != "no answer")
    return hall / len(unans)

fft_squad_rows = run_eval(fft_model, squad_val_s, "fft_squad.jsonl")
fft_finqa_rows = run_eval(fft_model, finqa_val_s, "fft_finqa.jsonl")

# SQuAD answerable scores
squad_ans = [r for r in fft_squad_rows if not r["is_impossible"]]
ems, f1s = zip(*[squad_em_f1(r["pred"], r["gold"]) for r in squad_ans])
print("\n=== FFT (FinQA-only) RESULTS ===")
print("SQuAD EM:", sum(ems)/len(ems))
print("SQuAD F1:", sum(f1s)/len(f1s))
print("SQuAD UHR:", compute_uhr(fft_squad_rows))
print("SQuAD OER:", compute_oer(fft_squad_rows))

# FinQA stats
print("FinQA stats:", finqa_numeric_stats(fft_finqa_rows))
print("FinQA NHR:", compute_nhr(fft_finqa_rows))
print("FinQA OER:", compute_oer(fft_finqa_rows))

def squad_summary(rows):
    ans = [r for r in rows if not r["is_impossible"]]
    ems, f1s = zip(*[squad_em_f1(r["pred"], r["gold"]) for r in ans])
    return {
        "EM": float(sum(ems)/len(ems)),
        "F1": float(sum(f1s)/len(f1s)),
        "UHR": float(compute_uhr(rows)),
        "OER80": float(compute_oer(rows))
    }

print("\n=== SQuAD SUMMARY TABLE ===")
print("Baseline:", squad_summary(baseline_squad_rows))
print("FFT:", squad_summary(fft_squad_rows))
print("LoRA finance-only:", squad_summary(finqa_only_squad_rows))
print("LoRA multitask:", squad_summary(mt_squad_rows))

print("\n=== FinQA SUMMARY TABLE ===")
print("Baseline:", finqa_numeric_stats(baseline_finqa_rows), "NHR", compute_nhr(baseline_finqa_rows), "OER", compute_oer(baseline_finqa_rows))
print("FFT:", finqa_numeric_stats(fft_finqa_rows), "NHR", compute_nhr(fft_finqa_rows), "OER", compute_oer(fft_finqa_rows))
print("LoRA finance-only:", finqa_numeric_stats(finqa_only_finqa_rows), "NHR", compute_nhr(finqa_only_finqa_rows), "OER", compute_oer(finqa_only_finqa_rows))
print("LoRA multitask:", finqa_numeric_stats(mt_finqa_rows), "NHR", compute_nhr(mt_finqa_rows), "OER", compute_oer(mt_finqa_rows))

ex = finqa_train[0]
print("keys:", ex.keys())

for k in ["program", "golden_program", "annotation", "qa"]:
    if k in ex:
        v = ex[k]
        print("\n", k, "type:", type(v))
        print(str(v)[:600])

from datasets import load_dataset

raw_finqa = load_dataset("ibm/finqa", trust_remote_code=True)
print(raw_finqa)
print("raw keys (train example):", raw_finqa["train"][0].keys())

ex = raw_finqa["train"][0]
print("keys:", ex.keys())

for k in ["program", "golden_program", "annotation", "qa", "exe_ans", "final_answer"]:
    if k in ex:
        print("\n", k, "type:", type(ex[k]))
        print(str(ex[k])[:800])

for k in ["pre_text", "post_text", "table"]:
    if k in ex:
        print("\n", k, "type:", type(ex[k]))
        v = ex[k]
        print(str(v)[:800])

print("splits:", list(raw_finqa.keys()))

for i in range(5):
    ex = raw_finqa["train"][i]
    print("\n---", i, "---")
    print("question:", ex["question"])
    print("final_result:", ex["final_result"])
    print("program_re:", ex["program_re"])

--- 0 ---
question: what is the the interest expense in 2009?
final_result: 380
program_re: divide(100, 100), divide(3.8, #0)

--- 1 ---
question: during the 2012 year , did the equity awards in which the prescribed performance milestones were achieved exceed the equity award compensation expense for equity granted during the year?
final_result: yes
program_re: multiply(607, 18.13), multiply(#0, const_1000), multiply(3.3, const_1000000), greater(#1, #2)

--- 2 ---
question: what was the total operating expenses in 2018 in millions
final_result: 41932
program_re: divide(9896, 23.6%)

--- 3 ---
question: what percentage of total cash and investments as of dec . 29 2012 was comprised of available-for-sale investments?
final_result: 53%
program_re: divide(14001, 26302)

--- 4 ---
question: what is the growth rate in net revenue in 2008?
final_result: -3.2%
program_re: subtract(959.2, 991.1), divide(#0, 991.1)

import re, math

CONST_MAP = {
    "const_1": 1.0,
    "const_10": 10.0,
    "const_100": 100.0,
    "const_1000": 1000.0,
    "const_10000": 10000.0,
    "const_100000": 100000.0,
    "const_1000000": 1000000.0,
}

def to_number(token):
    if token is None:
        return None
    if isinstance(token, (int, float)):
        return float(token)

    s = str(token).strip()
    # remove trailing artifacts like "step 1"
    s = re.sub(r"\bstep\s*\d+\b.*$", "", s).strip()

    # constants
    if s in CONST_MAP:
        return CONST_MAP[s]

    s = s.replace(",", "")
    s = re.sub(r"[$£€]", "", s)

    # percentages like "23.6%" => 0.236  (IMPORTANT: treat as fraction!)
    if s.endswith("%"):
        try:
            return float(s[:-1]) / 100.0
        except:
            return None

    try:
        return float(s)
    except:
        return None

def safe_div(a, b):
    if a is None or b is None or b == 0:
        return None
    return a / b

def apply_op(op, args):
    op = op.lower()
    if op in ["add", "plus"]:
        return args[0] + args[1]
    if op in ["subtract", "sub", "minus"]:
        return args[0] - args[1]
    if op in ["multiply", "mul", "times"]:
        return args[0] * args[1]
    if op in ["divide", "div"]:
        return safe_div(args[0], args[1])

    # boolean comparisons (return "yes"/"no" to match dataset)
    if op == "greater":
        return "yes" if args[0] > args[1] else "no"
    if op == "less":
        return "yes" if args[0] < args[1] else "no"
    if op == "equal":
        return "yes" if args[0] == args[1] else "no"

    raise ValueError(f"Unsupported op: {op}")

def split_calls(program_text):
    """
    Split "divide(100, 100), divide(3.8, #0)" into ["divide(100, 100)", "divide(3.8, #0)"]
    without breaking commas inside parentheses.
    """
    s = program_text.strip()
    # remove trailing "step ..." if appended
    s = re.sub(r"\bstep\s*\d+\b.*$", "", s).strip()

    calls = []
    buf = []
    depth = 0
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth-1)

        if ch == "," and depth == 0:
            call = "".join(buf).strip()
            if call:
                calls.append(call)
            buf = []
        else:
            buf.append(ch)
    last = "".join(buf).strip()
    if last:
        calls.append(last)
    return calls

def parse_program_re(prog):
    """
    prog is raw_finqa ex["program_re"] string.
    Returns steps: [{"out":"#0","op":"divide","args":["100","100"]}, ...]
    """
    if prog is None:
        return None
    if isinstance(prog, list):
        prog = " ".join([str(x) for x in prog])
    if not isinstance(prog, str):
        return None

    calls = split_calls(prog)
    steps = []
    for i, call in enumerate(calls):
        m = re.match(r"\s*([A-Za-z_]+)\((.*)\)\s*$", call)
        if not m:
            return None
        op = m.group(1).strip()
        argstr = m.group(2).strip()
        args = [a.strip() for a in split_args(argstr)]
        steps.append({"out": f"#{i}", "op": op, "args": args})
    return steps

def split_args(argstr):
    """Split args inside a call; in this dataset it's simple, but keep robust."""
    # no nested parentheses expected inside args, but keep safe
    parts = []
    buf = []
    depth = 0
    for ch in argstr:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth-1)

        if ch == "," and depth == 0:
            part = "".join(buf).strip()
            if part:
                parts.append(part)
            buf = []
        else:
            buf.append(ch)
    last = "".join(buf).strip()
    if last:
        parts.append(last)
    return parts

def execute_program_re(prog):
    steps = parse_program_re(prog)
    if steps is None:
        return None, False, False  # value, parsed, executed
    env = {}
    last = None
    try:
        for s in steps:
            vals = []
            for a in s["args"]:
                if a in env:
                    vals.append(env[a])
                else:
                    vals.append(to_number(a))
            # if any numeric missing for numeric ops -> fail execute
            if s["op"].lower() not in ["greater","less","equal"] and any(v is None for v in vals):
                return None, True, False
            last = apply_op(s["op"], vals)
            env[s["out"]] = last
        return last, True, True
    except Exception:
        return None, True, False

def normalize_final_result(fr):
    s = str(fr).strip().lower()
    if s in ["yes","no"]:
        return s
    # keep percentage as float fraction for comparison, but also store % form
    n = to_number(s)
    return n if n is not None else s

def eval_gold_exec(split, n=500):
    total = 0
    parsed = 0
    executed = 0
    match = 0

    for i in range(min(n, len(split))):
        ex = split[i]
        gold = normalize_final_result(ex["final_result"])
        pred, p_ok, e_ok = execute_program_re(ex["program_re"])

        total += 1
        parsed += int(p_ok)
        executed += int(e_ok)

        if not e_ok:
            continue

        # compare
        if isinstance(gold, str):  # yes/no
            if isinstance(pred, str) and pred.lower() == gold:
                match += 1
        else:
            # numeric compare with tolerance
            if isinstance(pred, (int,float)):
                abs_err = abs(pred - gold)
                rel_err = abs_err / (abs(gold) + 1e-9)
                if abs_err <= 0.1 or rel_err <= 0.01:
                    match += 1

    return {
        "total": total,
        "parsed_rate": parsed/total,
        "executed_rate": executed/total,
        "gold_exec_match_rate": match/total
    }

print("Gold exec sanity (train):", eval_gold_exec(raw_finqa["train"], n=500))
print("Gold exec sanity (val):", eval_gold_exec(raw_finqa["validation"], n=300))

from datasets import Dataset

def build_prog_ds(split):
    rows = []
    for ex in split:
        ctx = build_finqa_context(ex)
        q = ex["question"]
        prog = ex["program_re"]
        if not ctx or not q or not prog:
            continue
        rows.append({"context": ctx, "question": q, "program": str(prog).strip()})
    return Dataset.from_list(rows)

train_prog = build_prog_ds(raw_finqa["train"])
val_prog   = build_prog_ds(raw_finqa["validation"])
print("Program DS sizes:", len(train_prog), len(val_prog))

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq
from peft import LoraConfig, get_peft_model, TaskType
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

base_name = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(base_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_name).to(device)

lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=16, lora_alpha=32, lora_dropout=0.05,
    bias="none",
    target_modules=["q","v"],
)
prog_model = get_peft_model(base_model, lora_cfg).to(device)
prog_model.print_trainable_parameters()

def make_prompt_prog(context, question):
    return (
        "You are given a financial context (text + table) and a question.\n"
        "Write a symbolic program using operators {divide,multiply,subtract,add,greater}.\n"
        "Use intermediate variables #0,#1,... produced in order.\n"
        "Return ONLY the program with comma-separated steps.\n\n"
        f"Context: {context}\n\n"
        f"Question: {question}\n\n"
        "Program:"
    )

def preprocess_prog(batch):
    prompts = [make_prompt_prog(c, q) for c, q in zip(batch["context"], batch["question"])]
    x = tokenizer(prompts, max_length=512, truncation=True)
    with tokenizer.as_target_tokenizer():
        y = tokenizer(batch["program"], max_length=128, truncation=True)
    x["labels"] = y["input_ids"]
    return x

train_prog_tok = train_prog.map(preprocess_prog, batched=True, remove_columns=train_prog.column_names)
val_prog_tok   = val_prog.map(preprocess_prog, batched=True, remove_columns=val_prog.column_names)

collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=prog_model)

args = Seq2SeqTrainingArguments(
    output_dir="lora_program_finqa",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    num_train_epochs=2,
    logging_steps=50,
    evaluation_strategy="steps",
    eval_steps=200,
    save_steps=200,
    save_total_limit=2,
    predict_with_generate=True,
    generation_max_length=128,
    bf16=True,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=prog_model,
    args=args,
    train_dataset=train_prog_tok,
    eval_dataset=val_prog_tok,
    data_collator=collator,
    tokenizer=tokenizer,
)

trainer.train()
prog_model.save_pretrained("adapter_program_finqa")
tokenizer.save_pretrained("adapter_program_finqa")
print("✅ Saved program adapter to adapter_program_finqa/")

@torch.inference_mode()
def gen_program(model, context, question):
    prompt = make_prompt_prog(context, question)
    inp = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    out = model.generate(**inp, max_new_tokens=128, do_sample=False, num_beams=1)
    return tokenizer.decode(out[0], skip_special_tokens=True).strip()

def exec_accuracy(model, split, n=300):
    total = 0
    parsed = 0
    executed = 0
    correct = 0

    for i in range(min(n, len(split))):
        ex = split[i]
        ctx = build_finqa_context(ex)
        q = ex["question"]
        gold = normalize_final_result(ex["final_result"])

        pred_prog = gen_program(model, ctx, q)
        pred_val, p_ok, e_ok = execute_program_re(pred_prog)

        total += 1
        parsed += int(p_ok)
        executed += int(e_ok)

        if not e_ok:
            continue

        if isinstance(gold, str):  # yes/no
            if isinstance(pred_val, str) and pred_val.lower() == gold:
                correct += 1
        else:
            if isinstance(pred_val, (int,float)):
                abs_err = abs(pred_val - gold)
                rel_err = abs_err / (abs(gold) + 1e-9)
                if abs_err <= 0.1 or rel_err <= 0.01:
                    correct += 1

    return {
        "n": total,
        "parsed_rate": parsed/total,
        "executed_rate": executed/total,
        "exec_acc": correct/total,
        "exec_acc_given_executed": correct/executed if executed else None
    }

print("Program→Exec accuracy (val):", exec_accuracy(prog_model, raw_finqa["validation"], n=300))

print("Program→Exec accuracy (val, full):", exec_accuracy(prog_model, raw_finqa["validation"], n=len(raw_finqa["validation"])))

import matplotlib.pyplot as plt
import numpy as np

models = ["Baseline", "FFT", "LoRA", "Multi-task"]
squad_f1 = [0.7709, 0.0409, 0.1426, 0.7381]

plt.figure(figsize=(8,5))
bars = plt.bar(models, squad_f1)

plt.title("SQuAD F1 Across Training Strategies")
plt.ylabel("F1 Score")
plt.ylim(0, 0.85)
plt.grid(axis="y", linestyle="--", alpha=0.6)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 0.02,
             f"{height:.2f}",
             ha='center')

plt.xticks(rotation=25)
plt.tight_layout()
plt.show()

squad_uhr = [0.4278, 1.0, 1.0, 0.2497]

plt.figure(figsize=(8,5))
bars = plt.bar(models, squad_uhr)

plt.title("Unanswerable Hallucination Rate (UHR)")
plt.ylabel("UHR")
plt.ylim(0, 1.1)
plt.grid(axis="y", linestyle="--", alpha=0.6)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 0.03,
             f"{height:.2f}",
             ha='center')

plt.xticks(rotation=25)
plt.tight_layout()
plt.show()

squad_oer = [0.0773, 0.1897, 0.1698, 0.0311]

plt.figure(figsize=(8,5))
bars = plt.bar(models, squad_oer)

plt.title("Overconfident Error Rate (OER)")
plt.ylabel("OER")
plt.ylim(0, 0.25)
plt.grid(axis="y", linestyle="--", alpha=0.6)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 0.01,
             f"{height:.2f}",
             ha='center')

plt.xticks(rotation=25)
plt.tight_layout()
plt.show()

labels = ["String EM", "Program Execution"]
values = [0.0011, 0.0589]

plt.figure(figsize=(6,5))
bars = plt.bar(labels, values)

plt.title("FinQA Accuracy: String vs Program Supervision")
plt.ylabel("Accuracy")
plt.ylim(0, 0.07)
plt.grid(axis="y", linestyle="--", alpha=0.6)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 0.002,
             f"{height:.3f}",
             ha='center')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

points = {
    "Baseline":   {"F1": 0.7709, "UHR": 0.4278},
    "FFT":        {"F1": 0.0409, "UHR": 1.0},
    "LoRA":       {"F1": 0.1426, "UHR": 1.0},
    "Multi-task": {"F1": 0.7381, "UHR": 0.2497},
}

plt.figure(figsize=(7,5))

xs = [points[k]["UHR"] for k in points]
ys = [points[k]["F1"]  for k in points]

plt.scatter(xs, ys)

for name in points:
    x = points[name]["UHR"]
    y = points[name]["F1"]
    plt.text(x + 0.01, y + 0.01, name)

plt.title("Trade-off: SQuAD Performance vs Hallucination Risk")
plt.xlabel("Unanswerable Hallucination Rate (UHR) ↓")
plt.ylabel("SQuAD F1 ↑")
plt.xlim(0, 1.05)
plt.ylim(0, 0.85)
plt.grid(True, linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()